$(document).ready(function(){
	$(".xiadan").click(function(){
		$('.zhedangceng').fadeIn('slow')
		$('.tanchukuang').fadeIn(500)
	})
	$('.close').click(function(){
		$('.zhedangceng').fadeOut('slow')
		$('.tanchukuang').fadeOut(200)
	})
})
